// <auto-generated />
using System;
using APBD_Kolos_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_Kolos_2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250613111542_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_Kolos_2.Models.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            ArtistId = 1,
                            BirthDate = new DateTime(2000, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "A",
                            LastName = "B"
                        },
                        new
                        {
                            ArtistId = 2,
                            BirthDate = new DateTime(2000, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "B",
                            LastName = "C"
                        },
                        new
                        {
                            ArtistId = 3,
                            BirthDate = new DateTime(2000, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "C",
                            LastName = "D"
                        },
                        new
                        {
                            ArtistId = 4,
                            BirthDate = new DateTime(2000, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "D",
                            LastName = "E"
                        },
                        new
                        {
                            ArtistId = 5,
                            BirthDate = new DateTime(2000, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "E",
                            LastName = "F"
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2.Models.Artwork", b =>
                {
                    b.Property<int>("ArtworkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtworkId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ArtworkId");

                    b.ToTable("Artwork");

                    b.HasData(
                        new
                        {
                            ArtworkId = 1,
                            ArtistId = 1,
                            Title = "ASADASDAd",
                            Year = 2012
                        },
                        new
                        {
                            ArtworkId = 2,
                            ArtistId = 2,
                            Title = "ASADA",
                            Year = 2013
                        },
                        new
                        {
                            ArtworkId = 3,
                            ArtistId = 3,
                            Title = "ASSDAd",
                            Year = 2014
                        },
                        new
                        {
                            ArtworkId = 4,
                            ArtistId = 4,
                            Title = "ADASDAd",
                            Year = 2015
                        },
                        new
                        {
                            ArtworkId = 5,
                            ArtistId = 5,
                            Title = "ASADqweqwdsad",
                            Year = 2016
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2.Models.Exhibition", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExhibitionId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GalleryId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfArtworks")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExhibitionId");

                    b.ToTable("Exhibition");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            EndDate = new DateTime(2021, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 1,
                            NumberOfArtworks = 4,
                            StartDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AA"
                        },
                        new
                        {
                            ExhibitionId = 2,
                            EndDate = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 1,
                            NumberOfArtworks = 5,
                            StartDate = new DateTime(2021, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AAB"
                        },
                        new
                        {
                            ExhibitionId = 3,
                            EndDate = new DateTime(2021, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 2,
                            NumberOfArtworks = 3,
                            StartDate = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AAC"
                        },
                        new
                        {
                            ExhibitionId = 4,
                            EndDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 2,
                            NumberOfArtworks = 6,
                            StartDate = new DateTime(2021, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AAD"
                        },
                        new
                        {
                            ExhibitionId = 5,
                            EndDate = new DateTime(2021, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 3,
                            NumberOfArtworks = 2,
                            StartDate = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AAE"
                        },
                        new
                        {
                            ExhibitionId = 6,
                            EndDate = new DateTime(2021, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GalleryId = 4,
                            NumberOfArtworks = 7,
                            StartDate = new DateTime(2021, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AAF"
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2.Models.ExhibitionArtwork", b =>
                {
                    b.Property<int>("ExhibitionId")
                        .HasColumnType("int");

                    b.Property<int>("ArtworkId")
                        .HasColumnType("int");

                    b.Property<decimal>("InsuranceValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric");

                    b.HasKey("ExhibitionId", "ArtworkId");

                    b.HasIndex("ArtworkId");

                    b.ToTable("Exhibition_Artwork");

                    b.HasData(
                        new
                        {
                            ExhibitionId = 1,
                            ArtworkId = 1,
                            InsuranceValue = 1200.33m
                        },
                        new
                        {
                            ExhibitionId = 2,
                            ArtworkId = 2,
                            InsuranceValue = 1040.24m
                        },
                        new
                        {
                            ExhibitionId = 3,
                            ArtworkId = 3,
                            InsuranceValue = 1030.64m
                        },
                        new
                        {
                            ExhibitionId = 4,
                            ArtworkId = 4,
                            InsuranceValue = 1110.65m
                        },
                        new
                        {
                            ExhibitionId = 5,
                            ArtworkId = 5,
                            InsuranceValue = 10055.92m
                        },
                        new
                        {
                            ExhibitionId = 6,
                            ArtworkId = 1,
                            InsuranceValue = 101120.46m
                        },
                        new
                        {
                            ExhibitionId = 7,
                            ArtworkId = 2,
                            InsuranceValue = 1012310.57m
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2.Models.Gallery", b =>
                {
                    b.Property<int>("GalleryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryID"));

                    b.Property<DateTime>("EstablishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GalleryID");

                    b.ToTable("Gallery");

                    b.HasData(
                        new
                        {
                            GalleryID = 1,
                            EstablishedDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "A"
                        },
                        new
                        {
                            GalleryID = 2,
                            EstablishedDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "B"
                        },
                        new
                        {
                            GalleryID = 3,
                            EstablishedDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "C"
                        });
                });

            modelBuilder.Entity("APBD_Kolos_2.Models.ExhibitionArtwork", b =>
                {
                    b.HasOne("APBD_Kolos_2.Models.Artwork", null)
                        .WithMany("ExhibitionArtworks")
                        .HasForeignKey("ArtworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_Kolos_2.Models.Exhibition", null)
                        .WithMany("ExhibitionArtworks")
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBD_Kolos_2.Models.Artwork", b =>
                {
                    b.Navigation("ExhibitionArtworks");
                });

            modelBuilder.Entity("APBD_Kolos_2.Models.Exhibition", b =>
                {
                    b.Navigation("ExhibitionArtworks");
                });
#pragma warning restore 612, 618
        }
    }
}
